Feature/78295 relatorio inclusao alimentacao cei
prefeiturasp/SME-Terceirizadas pull request #1727
Opened 2022-11-07 18:11 UTC by rodolphoazeredo

2022-11-07 19:08 UTC, CalvinRossinhole requested changes

2022-11-07 19:08 UTC, CalvinRossinhole commented on sme_terceirizadas/relatorios/relatorios.py
> +            for faixa in FaixaEtaria.objects.all():
@rodolphoazeredo não faz sentido pegar todas as faixas, você só precisa exibir as faixas que possuem algum dado e que estão atreladas a inclusão que ta printando o relatorio

2022-11-07 19:08 UTC, CalvinRossinhole commented on sme_terceirizadas/relatorios/relatorios.py
> +                    quantidade_inclusao = 0
@rodolphoazeredo complementando o comentário acima, nesse caso, não teria um default com quantidade 0 quando não tem dados pra uma faixa, o relatório funciona diferente da solicitação. No relatório a gente só exibe as faixas que possuem dados, os usuários não querem saber quais faixas não tiveram pedido.

2022-11-07 19:08 UTC, CalvinRossinhole commented on sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
> +        # AQUI
remover comentario

2022-11-07 19:55 UTC, rodolphoazeredo commented on sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
> +        # AQUI
Removido

2022-11-07 19:56 UTC, rodolphoazeredo commented on sme_terceirizadas/relatorios/relatorios.py
> +            for faixa in FaixaEtaria.objects.all():
Eu fiz de acordo com os critérios e o protótipo que ta na história.

2022-11-16 19:25 UTC, CalvinRossinhole approved these changes

2022-11-16 19:31 UTC, merged